---
- name: Deploy RKE2 on DigitalOcean Droplet
  hosts: rke2_nodes
  become: yes
  vars:
    rke2_version: v1.24.9+rke2r1
    ansible_ssh_private_key_file: id_rsa
    ansible_user: root

  tasks:
    - name: Clean DNF cache
      command: dnf clean all

    - name: Update DNF cache
      dnf:
        update_cache: yes

    - name: Update all packages
      dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install required packages
      dnf:
        name:
          - curl
          - tar
          - iptables
        state: present

    # to learn more about this script
    - name: Download RKE2 install script
      get_url:
        url: https://get.rke2.io
        dest: /root/rke2-install.sh
        mode: '0700'

    - name: Create RKE2 config directory
      file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'
    # to reconfig
    - name: Configure RKE2
      copy:
        content: |
          write-kubeconfig-mode: "0644"
          tls-san:
            - {{ ansible_host }}
        dest: /etc/rancher/rke2/config.yaml

    - name: Install RKE2
      shell: sh /root/rke2-install.sh
      args:
        creates: /usr/local/bin/rke2

    - name: Enable and start RKE2 server service
      systemd:
        name: rke2-server.service
        enabled: yes
        state: started

    - name: Wait for RKE2 to be ready
      wait_for:
        path: /var/lib/rancher/rke2/server/node-token
        state: present
        timeout: 600

    - name: Add RKE2 bin directory to PATH
      lineinfile:
        path: /root/.bashrc
        line: 'export PATH=$PATH:/var/lib/rancher/rke2/bin'
        create: yes

    - name: Set KUBECONFIG environment variable
      lineinfile:
        path: /root/.bashrc
        line: 'export KUBECONFIG=/etc/rancher/rke2/rke2.yaml'
        create: yes

    - name: Wait for kubelet to be ready
      command: /var/lib/rancher/rke2/bin/kubectl get nodes
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: kubectl_result
      until: kubectl_result.rc == 0
      retries: 30
      delay: 10

    - name: Get cluster info
      command: /var/lib/rancher/rke2/bin/kubectl cluster-info
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: cluster_info

    - name: Display cluster info
      debug:
        var: cluster_info.stdout_lines

    - name: Get node status
      command: /var/lib/rancher/rke2/bin/kubectl get nodes
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: node_status

    - name: Display node status
      debug:
        var: node_status.stdout_lines